language: python
cache:
  pip
python:
#  - "2.7"
  - "3.3"

install:
  - "sudo apt-get install -y libopenblas-dev* liblapack-dev* gfortran"
#  - "sudo apt-get install -y python-scipy python3-scipy"
  - "sudo apt_get install -y python3-numpy python3-scipy python3-matplotlib ipython3 ipython3-notebook python3-pandas python3-sympy python3-nose"
  - "pip install --upgrade pip"
  - "pip install coveralls"
  - "pip install -r pip_packages.txt"
#  - "travis_wait pip install scipy"

script:
  nosetests --with-coverage --cover-package=tuna

after_success:
  coveralls

sudo: required
