language: python
cache:
  pip
python:
  - "3.3"

install:
  - "sudo apt-get install -y libopenblas-dev* liblapack-dev* gfortran"
  - "pip install --upgrade pip"
  - "pip install coveralls"
  - "pip install -r pip_packages.txt"
  - "travis_wait pip install scipy"

script:
  nosetests --with-coverage --cover-package=tuna test/unit/unit_console/unit_test_console.py
  nosetests --with-coverage --cover-package=tuna test/unit/unit_io/unit_test_io_adhoc.py test/unit/unit_io/unit_test_io_adhoc_ada.py test/unit/unit_io/unit_test_io_can.py
  nosetests --with-coverage --cover-package=tuna test/unit/unit_log/unit_test_client.py test/unit/unit_log/unit_test_server.py
  nosetests --with-coverage --cover-package=tuna test/unit/unit_repo/unit_test_client.py test/unit/unit_repo/unit_test_local_disk.py
  nosetests --with-coverage --cover-package=tuna test/unit/unit_tools/unit_test_client.py test/unit/unit_tools/unit_test_get_pixel_neighbours.py

after_success:
  coveralls

sudo: required
