language: python
cache:
  pip
python:
  - "3.3"

install:
  - "sudo apt-get install -y libopenblas-dev* liblapack-dev* gfortran*"
  - "pip install --upgrade pip"
  - "pip install coveralls"
  - "pip install numpy"
  - "pip install -r pip_packages.txt"
  - "pip install scipy"

script:
  nosetests --with-coverage --cover-package=tuna

after_success:
  coveralls

sudo: required
