language: python
cache:
  pip
python:
#  - "2.7"
  - "3.3"

install:
  - "sudo apt-get install -y libopenblas-dev* liblapack-dev* gfortran"
  - "sudo apt-get install -y python3-numpy"
  #- "sudo apt-cache search scipy"
  - "sudo apt-get install -y python3-scipy"	
  #  - "sudo apt_get install -y qt4-qmake"
  # It might be necessary to ln qt4-qmake into qmake; in Fedora 21 I had to.
  - "pip install --upgrade pip"
  - "pip install coveralls"
  - "pip install -r pip_packages.txt"
  - "travis_wait pip install scipy"
  - "git clone https://github.com/evertrol/mpyfit.git"
  - "cd mpyfit; python setup.py install; cd .."

script:
  nosetests --with-coverage --cover-package=tuna

after_success:
  coveralls

sudo: required
