language: python
cache:
  pip
python:
#  - "2.7"
  - "3.3"

addons:
  apt:
    packages:
    - gfortran
    - libopenblas-dev
    - liblapack-dev
    - python3-numpy
    - python3-scipy

install:
  - "pip install --upgrade pip"
  - "pip install coveralls"
  - "pip install -r pip_packages.txt"
  - "travis_wait pip install scipy"
  - "git clone https://github.com/evertrol/mpyfit.git"
  - "cd mpyfit; python setup.py install; cd .."

script:
  nosetests -s --with-coverage --cover-package=tuna

after_success:
  coveralls

#sudo: required
sudo: false
