language: python
cache:
  pip
python:
#  - "2.7"
  - "3.3"

install:
  - "sudo apt-get install -y libopenblas-dev* liblapack-dev* gfortran"
  - "sudo apt-get install -y python3-numpy python3-scipy*"
  - "pip install --upgrade pip"
  - "pip install coveralls"
  - "pip install -r pip_packages.txt"
  - "travis_wait pip install scipy"
  - "git clone https://github.com/evertrol/mpyfit.git"
  - "cd mpyfit; python setup.py install"

script:
  nosetests --with-coverage --cover-package=tuna

after_success:
  coveralls

sudo: required
